apiVersion: v1
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
metadata:
  name: {{ include "mongodb.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
kind: Secret
type: {{ .Values.secrettype }}